add support for 'staskfarm cmd param [param]...'
If more than one arg is supplied, assume that it's a single command
plus a parameter list, and use that to create the multi-prog config.

Otherwise, keep original behaviour of 'staskfarm command_filename.txt'

Update the README file to reflect the second mode of operation.

diff --git a/staskfarm b/staskfarm
--- a/staskfarm
+++ b/staskfarm
@@ -16,11 +16,21 @@
 # * the number of commands must match exactly the number of slurm tasks (-n),
 #   which means updating two files if you wish to add or remove tasks
 #
+# 2017-10-17 <paddy@tchpc.tcd.ie>
+# Inspired by forked version by cmeesters, add a second mode of operation:
+# * original: staskfarm commands.txt
+# * new: staskfarm command param [param]...
+#   In this mode, allow a parameter sweep, prefaced by a single command. It
+#   may be easier than creating the equivalent commands.txt, and allows
+#   for shell globbing for example to generate the param list.
 
 
 function usage {
 	cat <<-EOM
 	Usage: $(basename $0) [-v] command_filename
+	  or:  $(basename $0) [-v] command param [param]...
+	
+	In the first mode of operation: $(basename $0) [-v] command_filename
 	
 	The <command_filename> must have one individual task per
 	line. The task can comprise of multiple bash shell commands,
@@ -45,6 +55,17 @@ function usage {
 	Enabling verbose mode prints each command to stdout as it is
 	read from the command file.
 	
+	In the second mode of operation: $(basename $0) [-v] command param [param]...
+	
+	The <command> is combined with each of the individual <param> parameters to
+	generate the list of tasks to be executed. The number of tasks will be equal
+	to the number of <param> values.
+	
+	The <param> values can either be a simple list (e.g. input1 input2...),
+	or a shell glob (e.g. *.inp).
+	
+	Note that no output redirection is performed in this mode.
+	
 	Limitations:
 	
 	* it writes the list of tasks to K files, where K is the value of
@@ -67,9 +88,9 @@ function usage {
 	
 	* no output redirection is performed, so any stdout/stderr will
 	  be sent to the slurm-NNNNN.out file by default. This can
-	  be changed by adding individual redirects to each task.
-	  Care must be taken in that case so that the output files
-	  have unique names/paths.
+	  be changed by adding individual redirects to each task (in the
+	  first mode of operation). Care must be taken in that case so
+	  that the output files have unique names/paths.
 	
 	Note that this program will create a temporary directory
 	(called .taskfarm_job_\${SLURM_JOB_ID}) in which to store
@@ -88,6 +109,7 @@ command_filename=""
 dummy_command=/bin/true
 # loop counter
 i=0
+# count of non-blank and non-comment lines: the number of actual commands
 ncommands=0
 
 
@@ -111,18 +133,6 @@ shift $(($OPTIND-1))
 if [ "$#" -eq "0" ]
 then
 	usage; exit 1
-else
-	command_filename=$1
-fi
-
-
-######################################################
-# Does the file exist?
-######################################################
-if [ ! -f "${command_filename}" ]
-then
-	echo "$(basename $0): error: commands file ${command_filename} does not exist. Exiting."
-	exit 1
 fi
 
 
@@ -133,17 +143,6 @@ if [ "x${SLURM_JOB_ID}" = "x" -o "x${SLURM_NTASKS}" = "x" ]
 then
 	echo "$(basename $0): error: must be executed from within a SLURM allocation. Exiting."
 	exit 1
-fi
-
-
-if [ "${verbose}" = "1" ]
-then
-	echo ""
-	echo "-------------------- $(basename $0) START --------------------"
-	echo "Reading commands from file: ${command_filename}."
-	echo "There are $(cat ${command_filename} | wc -l) lines in the file."
-	echo "They will be spread over the ${SLURM_NTASKS} processors:   ${SLURM_TASKS_PER_NODE} tasks on ${SLURM_NODELIST}"
-	#md5sum ${command_filename}
 fi
 
 
@@ -171,49 +170,161 @@ mkdir .taskfarm_job_${SLURM_JOB_ID}
 
 
 ######################################################
-# Warn if no output redirection
+# Two modes of operation:
+# 1 if ($# == 1) then we've supplied a command_filename
+#   and go with the previous logic
+# 2 else we've supplied a command and a list of params,
+#   so generate the tasks based on those
 ######################################################
-if [ "${verbose}" = "1" ] && ! grep -q '>' ${command_filename}
+
+
+if [ "$#" -eq "1" ]
 then
-	echo ""
-	echo "WARNING: there is no individual task output redirection in the ${command_filename}"
-	echo "         file. This could potentially be a problem. Output of all individual"
-	echo "         tasks will likely be merged in the slurm output file ('slurm-${SLURM_JOB_ID}.out')."
-	echo ""
-fi
+	######################################################
+	# Mode 1: command_filename
+	######################################################
 
+	command_filename=$1
 
-######################################################
-# Main loop:
-# read the file, line by line, and create the
-# individual multi-prog shell scripts
-######################################################
-while read line
-do
-	# ignore blank lines and comment lines
-	if [[ $line =~ ^[[:blank:]]*# || $line =~ ^[[:blank:]]*$ ]]
+	######################################################
+	# Does the file exist?
+	######################################################
+	if [ ! -f "${command_filename}" ]
 	then
-		if [ "${verbose}" = "1" ]
-		then
-			echo "Skipping blank and comment lines"
-		fi
-		continue
+		echo "$(basename $0): error: commands file ${command_filename} does not exist. Exiting."
+		exit 1
 	fi
+
 
 	if [ "${verbose}" = "1" ]
 	then
-		echo "Adding the following line to .taskfarm_job_${SLURM_JOB_ID}/${i}.sh:     $line"
+		echo ""
+		echo "-------------------- $(basename $0) START --------------------"
+		echo "Reading commands from file: ${command_filename}."
+		echo "There are $(cat ${command_filename} | wc -l) lines in the file."
+		echo "They will be spread over the ${SLURM_NTASKS} processors:   ${SLURM_TASKS_PER_NODE} tasks on ${SLURM_NODELIST}"
+		#md5sum ${command_filename}
 	fi
 
-	echo $line >> .taskfarm_job_${SLURM_JOB_ID}/${i}.sh
 
-	# increment, modulo the number of tasks
-	(( i = (i + 1) % ${SLURM_NTASKS} ))
+	######################################################
+	# Warn if no output redirection
+	######################################################
+	if [ "${verbose}" = "1" ] && ! grep -q '>' ${command_filename}
+	then
+		echo ""
+		echo "WARNING: there is no individual task output redirection in the ${command_filename}"
+		echo "         file. This could potentially be a problem. Output of all individual"
+		echo "         tasks will likely be merged in the slurm output file ('slurm-${SLURM_JOB_ID}.out')."
+		echo ""
+	fi
 
-	# increment the total number of commands
-	(( ncommands++ ))
-done < ${command_filename}
 
+	######################################################
+	# Main loop:
+	# read the file, line by line, and create the
+	# individual multi-prog shell scripts
+	######################################################
+	while read line
+	do
+		# ignore blank lines and comment lines
+		if [[ $line =~ ^[[:blank:]]*# || $line =~ ^[[:blank:]]*$ ]]
+		then
+			if [ "${verbose}" = "1" ]
+			then
+				echo "Skipping blank and comment lines"
+			fi
+			continue
+		fi
+
+		if [ "${verbose}" = "1" ]
+		then
+			echo "Adding the following line to .taskfarm_job_${SLURM_JOB_ID}/${i}.sh:     $line"
+		fi
+
+		echo $line >> .taskfarm_job_${SLURM_JOB_ID}/${i}.sh
+
+		# increment, modulo the number of tasks
+		(( i = (i + 1) % ${SLURM_NTASKS} ))
+
+		# increment the total number of commands
+		(( ncommands++ ))
+	done < ${command_filename}
+
+else
+	######################################################
+	# Mode 2: command + param list
+	######################################################
+
+	command=$1
+
+	######################################################
+	# Does the file exist?
+	######################################################
+	if [ ! "which ${command}" ]
+	then
+		echo "$(basename $0): error: taskfarm command ${command} does not exist. Exiting."
+		exit 1
+	fi
+
+
+	if [ "${verbose}" = "1" ]
+	then
+		echo ""
+		echo "-------------------- $(basename $0) START --------------------"
+		echo "Using command: ${command} with $# parameters."
+		echo "They will be spread over the ${SLURM_NTASKS} processors:   ${SLURM_TASKS_PER_NODE} tasks on ${SLURM_NODELIST}"
+		#md5sum ${command_filename}
+	fi
+
+
+	######################################################
+	# Warn if no output redirection
+	######################################################
+	if [ "${verbose}" = "1" ]
+	then
+		echo ""
+		echo "WARNING: there is no individual task output redirection."
+		echo "         This could potentially be a problem. Output of all individual"
+		echo "         tasks will likely be merged in the slurm output file ('slurm-${SLURM_JOB_ID}.out')."
+		echo ""
+	fi
+
+
+	######################################################
+	# Main loop:
+	# loop over the parameters, and create the
+	# individual multi-prog shell scripts
+	######################################################
+
+	# the first positional arg is the 'command' variable, which we've saved above
+	# remove it from the list
+	shift
+
+	# just in case of quoted parameters (e.g. filenames with spaces)
+	SAVEIFS=$IFS
+	IFS=$(echo -en "\n\b")
+
+	for param in $*
+	do
+		line="${command} ${param}"
+
+		if [ "${verbose}" = "1" ]
+		then
+			echo "Adding the following line to .taskfarm_job_${SLURM_JOB_ID}/${i}.sh:     $line"
+		fi
+
+		echo $line >> .taskfarm_job_${SLURM_JOB_ID}/${i}.sh
+
+		# increment, modulo the number of tasks
+		(( i = (i + 1) % ${SLURM_NTASKS} ))
+
+		# increment the total number of commands
+		(( ncommands++ ))
+	done
+
+	IFS=$SAVEIFS
+fi
 
 ######################################################
 # Sanity check: if the number of commands is less
@@ -225,7 +336,7 @@ while (( ${ncommands} < ${SLURM_NTASKS} ))
 do
 	if [ "${verbose}" = "1" ]
 	then
-		echo "Adding the dummy command to .taskfarm_job_${SLURM_JOB_ID}/${i}.sh:     $line"
+		echo "Adding the dummy command to .taskfarm_job_${SLURM_JOB_ID}/${i}.sh:     ${dummy_command}"
 	fi
 
 	echo "${dummy_command}" >> .taskfarm_job_${SLURM_JOB_ID}/${i}.sh
