better error message upon parsing errors

diff --git a/staskfarm b/staskfarm
--- a/staskfarm
+++ b/staskfarm
@@ -160,7 +160,7 @@ for (( ii = 0; ii < $_our_args; ii++)); do
 done
 
 for (( ii = 0; ii < ${#_positionals[@]}; ii++)); do
-    eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
+    eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "ERROR: argument parsing not successful. Please report this error." 1
 done
 
 ######################################################
